(WIP): add CES api calls
Huawei-IRC-Cloud-Telemetry-Engineering/opentelemetry-collector-contrib pull request #24
Opened 2024-07-23 14:00 UTC by narcis96

2024-07-24 15:53 UTC, heitorganzeli requested changes

2024-07-24 15:53 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/config.yaml
> +    project_id: 059174727d164185aaa3fc48e756b820
don't commit this file.

we can share this configs separately and do an example on readme. but, it shouldn't contain anything private like credentials or project id

2024-07-24 15:53 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/receiver.go
>  func (rcvr *cesReceiver) generateMetrics(numberOfMetrics int) pmetric.Metrics {
method name also needs to be updated. maybe `receiveMetrics`

2024-07-24 15:53 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/receiver.go
> +	rcvr.logger.Sugar().Info(*response.Metrics)
Sugar logs might impact performance . might be good to add a `TODO` to review them later

2024-07-24 15:53 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/receiver.go
> +			// Assuming we want to store dimensions as labels
we need to create a README explaining this assumptions. and, how things are mapped from CES to internal format.

it can be a `TODO` for now

2024-07-25 08:05 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/config.yaml
> +    project_id: 059174727d164185aaa3fc48e756b820
yes yes. completely agree.

2024-07-25 08:06 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/receiver.go
>  func (rcvr *cesReceiver) generateMetrics(numberOfMetrics int) pmetric.Metrics {
this method will actually need to be removed and replaced by the one that uses the real metrics.

2024-08-02 09:38 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/receiver.go
> +			// Assuming we want to store dimensions as labels
readme added

2024-08-02 09:39 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/receiver.go
> +	rcvr.logger.Sugar().Info(*response.Metrics)
removed

2024-08-02 13:53 UTC, heitorganzeli requested changes
i'll keep reviewing the other files later today or next week.

well done so far

2024-08-02 13:53 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/README.md
> +
besides the final examples, you could add a brief description and maybe a table explaining the main field changes

we could discuss the changes in the stand up/ team meeting in case there's any complex change

2024-08-02 13:53 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/README.md
> +                    "publicip_id":  "test-baae-4dd9-ad3f-1234",
i don't know otel format that deeply, but `publicip_id` looks like a resource or maybe scope metric attribute.

what was your logic to decide  where to put the labels?

i was initially thinking that a resource would be for example an ECS instance. then this mapping would need to be changed. do you know how other receivers are doing it?

2024-08-02 13:53 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/config.go
> +	// How often Cloud Eye aggregates data.
maybe: How retrieved data from Cloud Eye is aggregated

2024-08-02 13:53 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/config.go
> +	}
instead of returning directly, it's better to create a collection of errors than return one validation error with all the invalid fields. then, developer can fix all at once

2024-08-02 13:53 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/internal/ces_to_otlp.go
> +	resource.Attributes().PutStr("project.id", projectID)
i think we might need to rethink these attributes a bit

my idea would be to put CES values as retrieval source. 

then the service, we might need to get from the namespace. 

for example `SYS.VPC` is the VPC huawei cloud service. Maybe there's a mapping of these accronyms on namespaces to the service name in the docs.

also might be good to add region somewhere

2024-08-02 16:03 UTC, heitorganzeli requested changes

2024-08-02 16:03 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/receiver.go
> +	to := now.UnixMilli()
this is not very accurate way setting to and from, since the actual execution times can vary, you could be either missing or adding some metrics twice.

so, a better way would be to store the last used `to` use that as the next from.

another issue is with delayed metrics. if i'm not mistaken, CES accepts metrics with 30min delay.

so, when retrieving, if request is based on now, collection might miss metrics which are 1min delayed, for example. because next request would exclude it.

this is complex to solve. but, we could add a `delay` configuration. 
and, we might also need to do some deduplication. maybe as a Processor.

2024-08-06 09:27 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +- `region_name`: The name of the Huawei Cloud region from which metrics are collected. For example, eu-west-101.
done

2024-08-06 09:28 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +- `project_id`: The ID of the project in Huawei Cloud. This is used to identify which project's metrics are to be collected.
done

2024-08-06 09:29 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +- `endpoint` (default: `http://localhost:5984`): The URL of the receiver endpoint
default from collector

2024-08-06 09:49 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +
added a table explaining the mapping.

2024-08-06 09:51 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/config.go
> +	// How often Cloud Eye aggregates data.
done

2024-08-06 09:52 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +- `initial_delay`: The delay before the first collection of metrics begins. This is also a duration field, such as 5s for 5 seconds.
done

2024-08-06 09:54 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +- `collection_interval` (default = `60s`): This receiver collects metrics on an interval. This value must be a string readable by Golang's [time.ParseDuration](https://pkg.go.dev/time#ParseDuration).
done

2024-08-06 09:55 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/internal/cest_to_otlp_test.go
> +package internal
fixed

2024-08-06 12:28 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/receiver.go
> +					rcvr.logger.Error(err.Error())
TODO added.

2024-08-06 12:28 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/receiver.go
> +					rcvr.logger.Error(err.Error())
todo added

2024-08-06 13:52 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/config.go
> +	}
done

2024-08-07 06:55 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +- `period`: The granularity of the metrics to be collected, in seconds. This determines how frequently the data points are recorded in CES. Possible values are 1, 300, 1200, 3600, 14400, and 86400.
done

2024-08-08 05:11 UTC, jayaganesh1997 commented on receiver/huaweicloudcesreceiver/config.go
> +		err = multierr.Append(err, errInvalidPeriod)
suggestion, should we output the current period as well so that it eases the debugging (like got value 2, want values 1, 10, 100...)? the same for others as well?

2024-08-08 05:11 UTC, jayaganesh1997 commented on receiver/huaweicloudcesreceiver/receiver.go
> +	go func() {
maybe I'm missing something big here, why is this in a go routine? this is the last execution on this function scope and blocks the return on the function
so you spin a goroutine and wait for it to complete and return, there's no other work in parallel?

2024-08-08 08:26 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/config.go
> +	"go.uber.org/multierr"
all the other receivers use "go.uber.org/multierr" instead of https://github.com/hashicorp/go-multierror so maybe stick to that as well.

2024-08-08 09:20 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/receiver.go
> +	go func() {
The use of a goroutine in this context follows the guidelines suggested in the [OpenTelemetry Collector receiver tutorial](https://opentelemetry.io/docs/collector/building/receiver/). 

The tutorial explains the importance of handling certain tasks asynchronously to ensure the receiver operates efficiently and also it doesn't block other operations.

I agree that, in this particular function scope, it appears that there isn't other parallel work being done.

2024-08-08 09:24 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +This receiver contains the implementation of the Huawei Cloud CES (Cloud Eye Service) receiver for the OpenTelemetry Collector. The receiver collects metrics from Huawei Cloud's CES service and sends
done

2024-08-08 09:24 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +- `region_name`: The name of the Huawei Cloud region from which metrics are collected. For example, eu-west-101. The full list of the available regions can be found [here](https://pkg.go.dev/github.c
done

2024-08-08 09:24 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +    - average: Calculates the average value over the period.
done

2024-08-08 09:24 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +Before running the application, you need to set the environment variables HUAWEICLOUD_SDK_AK and HUAWEICLOUD_SDK_SK in your local environment. Here’s how you can do it:
done

2024-08-08 09:32 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/config.go
> +		err = multierr.Append(err, errInvalidPeriod)
done

2024-08-08 10:25 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +                    "publicip_id":  "test-baae-4dd9-ad3f-1234",
region name added.
the problem is that the scope contains name and version only and the metadata is a map that fits much better the metric dimensions from huawei ces response

2024-08-08 11:19 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +## Field Mapping
done

2024-08-08 11:20 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/internal/ces_to_otlp.go
> +	resource.Attributes().PutStr("project.id", projectID)
done

2024-08-08 11:53 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +This receiver contains the implementation of the Huawei Cloud CES (Cloud Eye Service) receiver for the OpenTelemetry Collector. The receiver collects metrics from Huawei Cloud's CES service and sends
done

2024-08-09 09:10 UTC, heitorganzeli approved these changes
great work

2024-08-09 09:11 UTC, merged