solve TODOs
Huawei-IRC-Cloud-Telemetry-Engineering/opentelemetry-collector-contrib pull request #40
Opened 2024-08-20 12:42 UTC by narcis96

2024-08-23 11:15 UTC, heitorganzeli requested changes
few things to update. great work overall

2024-08-23 11:15 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/receiver.go
> +func (rcvr *cesReceiver) listDataPoints(ctx context.Context, metricDefinitions []model.MetricInfoList) map[string]internal.MetricData {
since this have a bit of complex logic with the last timestamps, it's good to add some godocs to the method

2024-08-23 11:15 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/receiver.go
> +		if delay == backoff.Stop {
isn't it better to use `>=`?  are you sure stop condition can always be reached?

2024-08-23 11:15 UTC, heitorganzeli commented on receiver/huaweicloudcesreceiver/receiver.go
> +func (rcvr *cesReceiver) listDataPointsForMetric(ctx context.Context, from, to time.Time, infoList model.MetricInfoList) (*model.ShowMetricDataResponse, error) {
this call with retry seems like a very common logic we should be using for all Huawei Cloud API calls.

i think it would be good to isolate it in a separate package, maybe on internal in a way to allow re-use

2024-08-28 09:01 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/README.md
> +- `retry_on_failure`
done

2024-08-28 09:03 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/receiver.go
> +		if delay == backoff.Stop {
not really. Please check https://github.com/cenkalti/backoff/blob/v4.3.0/backoff.go#L36

2024-08-28 10:37 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/receiver.go
> +func (rcvr *cesReceiver) listDataPointsForMetric(ctx context.Context, from, to time.Time, infoList model.MetricInfoList) (*model.ShowMetricDataResponse, error) {
that makes perfect sense. modified.

2024-08-29 13:07 UTC, heitorganzeli reviewed
a few small things

2024-08-29 14:27 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/internal/backoff_test.go
> +func TestMakeAPICallWithRetry_ThrottlingMaxRetries(t *testing.T) {
correct. renamed.

2024-08-29 14:30 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/internal/backoff_test.go
> +	cancel() // Immediately cancel the context
got it. Test changed so that the context is canceled midway.

2024-08-29 14:30 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/internal/backoff_test.go
> +func TestMakeAPICallWithRetryServerShutdown(t *testing.T) {
test changed so that the channel is closed midway.

2024-08-29 15:18 UTC, merged