add huaweicloudlogsreceiver skelethon
Huawei-IRC-Cloud-Telemetry-Engineering/opentelemetry-collector-contrib pull request #44
Opened 2024-09-04 09:23 UTC by narcis96

2024-09-11 15:34 UTC, heitorganzeli requested changes

2024-09-11 15:34 UTC, heitorganzeli commented on receiver/huaweicloudlogsreceiver/internal/lts_to_otlp_test.go
> +				for key, value := range tt.ltsLogs[i].Labels {
do you also need to check if len of `logRecord.Attributes` is the same as `tt.ltsLogs[i].Labels`

2024-09-11 15:34 UTC, heitorganzeli commented on receiver/huaweicloudlogsreceiver/receiver.go
> +	close(rcvr.shutdownChan)
i think that for this to work properly, `shutdownChan` should be unbuffered chan instead of buffered of one.

so that the consumer would need to execute before you get to close statement

2024-09-13 11:38 UTC, narcis96 commented on receiver/huaweicloudlogsreceiver/receiver.go
> +	close(rcvr.shutdownChan)
> so that the consumer would need to execute before you get to close statement

I don't think so. Check:

-  https://go.dev/play/p/7s9Fb4snLF6
- https://stackoverflow.com/questions/29269850/why-do-i-receive-values-from-a-closed-channel
- https://go.dev/ref/spec#Close
- ![Uploading close.PNG…]()

2024-09-13 11:59 UTC, narcis96 commented on receiver/huaweicloudlogsreceiver/internal/lts_client.go
> +// This interface should have all the function defined inside https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/v0.1.110/services/lts/v2/lts_client.go
correct. modified

2024-09-13 13:27 UTC, narcis96 commented on receiver/huaweicloudlogsreceiver/internal/lts_to_otlp.go
> +const layout = "2006-01-02/15:04:05"
> is this guaranteed and documented by the service or, does it depend on the log.

Unfortunately I did not found any documentation around it. The only thing I found is https://support.huaweicloud.com/intl/en-us/api-lts/ListLogs.html#section6

> also do you know what TZ it uses? it's important to properly convert the time.

The query request gets UTC so the assumption is that UTC will be used for the response as well.
Added a comment for that.

2024-09-13 13:31 UTC, narcis96 commented on receiver/huaweicloudlogsreceiver/internal/lts_to_otlp.go
> +	re := regexp.MustCompile(pattern)
> using regex here might be too expensive. i think it would be more performant to just split on the first space. and, then parse the timestamp.

I am not sure if the first space is a good enough assumption so that's why I prefered the regex.
 

> in any case, if regex is needed, it's better to Compile it outside of the loop, a package constant/var in this case to avoid compiling it multiple times

good point. moved it away from the function.

2024-09-13 13:40 UTC, narcis96 commented on receiver/huaweicloudlogsreceiver/internal/lts_to_otlp_test.go
> +				for key, value := range tt.ltsLogs[i].Labels {
done.

2024-09-13 13:40 UTC, narcis96 commented on receiver/huaweicloudlogsreceiver/config.go
> +	errMissingRegionID  = errors.New(`"region_id" is not specified in config`)
done

2024-09-13 13:47 UTC, narcis96 commented on receiver/huaweicloudcesreceiver/config_test.go
> +	"github.com/open-telemetry/opentelemetry-collector-contrib/internal/huawei"
make lint applied. it does not complain

2024-09-16 08:53 UTC, heitorganzeli commented on receiver/huaweicloudlogsreceiver/internal/lts_to_otlp.go
> +const layout = "2006-01-02/15:04:05"
to me, this actually looks like the original log line from the system. so, the format would actually depend on what is configured on the log stream.

would you be able to test if thats the case? like, creating some test to send different types/formats of log lines

if so, this layout pattern and the regex to find the time on the content could come from a configuration param

2024-10-24 13:54 UTC, narcis96 commented on receiver/huaweicloudlogsreceiver/internal/lts_to_otlp.go
> +const layout = "2006-01-02/15:04:05"
timestamp removed

2024-10-24 14:20 UTC, heitorganzeli approved these changes

2024-10-24 14:20 UTC, heitorganzeli commented on internal/huawei/client_config_test.go
> +// SPDX-License-Identifier: Apache-2.0
do you need to add this to all files? I think some of them don't have it

2024-10-29 09:24 UTC, merged